conda_dir:
  /home/sdp/miniconda3/envs/pmed/
log_dir:
  example/log/

data_dir:
  example/
vcf_file:
  example/example.8-9.vcf.gz
database_IDs:
  example/database_IDs.txt
query_IDs:
  example/query_IDs.txt
ref_map:
  example/example.8-9.map
out_dir:
  example/segments/
encoding_file:
  example/example_encoding.txt
sample_IDs_file:
  example/sample_IDs.txt

cpp_bin_dir:
  cpp/bin/
cpp_src_dir:
  cpp/src/
cpp_include_dir:
  cpp/include/

python_dir:
  python/scripts/

k:
  20
delim:
  space

htslib_dir:
  lib/htslib/
faisslib_dir:
  lib/faiss/
