home_dir:
./
conda_dir:
/home/sdp/miniconda3/envs/pm
cpp_bin_dir:
cpp/bin/
cpp_src_dir:
cpp/src/
cpp_include_dir:
cpp/include/
cpp_configs_dir:
cpp/configs/
python_dir:
python/scripts/
data_dir:
/home/sdp/precision-medicine/data/ped_sim_data/GBR_large/
vcf_file:
/home/sdp/precision-medicine/example/example.vcf
map_file:
/home/sdp/precision-medicine/example/example.map
encoding_file:
/home/sdp/precision-medicine/example/example_encoding.txt
sample_IDs_file:
/home/sdp/precision-medicine/example/samples_IDs.txt
query_file:
/home/sdp/precision-medicine/example/samples_query.txt
out_dir:
/home/sdp/precision-medicine/example/segments/
out_base_name:
example.data
segment_size:
1
