conda_pmed:
  conda_environments/pmed.yaml
conda_model:
  conda_environments/torch-cpu.yaml
conda_faiss:
  conda_environments/faiss-cpu.yaml

root_dir:
  example/
log_dir:
  example/log/
benchmark_dir:
  example/benchmark/
vcf_segments_dir:
  example/vcf_segments/
encodings_dir:
  example/encodings/
embeddings_dir:
  example/embeddings/
faiss_index_dir:
  example/faiss_index/
faiss_results_dir:
  example/faiss_results/
compare_dir:
  example/compare/

vcf_file:
  example/small_example.8.vcf.gz
ref_map:
  example/small_example.8.map  
database_IDs:
  example/database_IDs.txt
query_IDs:
  example/query_IDs.txt
encoding_file:
  encoding.txt
ilash_config:
  example/iLASH-example.config

cpp_bin_dir:
  cpp/bin/
cpp_src_dir:
  cpp/src/
cpp_include_dir:
  cpp/include/

python_dir:
  python/scripts/
model_dir:
  pytorch/
model_checkpoint:
  /home/sdp/precision-medicine/last.ckpt
batch_size:
  128
n_workers:
  112

k:
  20
delim:
  space

htslib_dir:
  lib/htslib/
faisslib_dir:
  lib/faiss/
