conda_pmed:
  pmed
conda_model:
  torch-cpu
conda_faiss:
  faiss-cpu

root_dir:
  /home/sdp/pmed_singularity/precision-medicine/example/
log_dir:
  /home/sdp/pmed_singularity/precision-medicine/example/log/
benchmark_dir:
  /home/sdp/pmed_singularity/precision-medicine/example/benchmark/
vcf_segments_dir:
  /home/sdp/pmed_singularity/precision-medicine/example/vcf_segments/
encodings_dir:
  /home/sdp/pmed_singularity/precision-medicine/example/encodings/
embeddings_dir:
  /home/sdp/pmed_singularity/precision-medicine/example/embeddings/
faiss_index_dir:
  /home/sdp/pmed_singularity/precision-medicine/example/faiss_index/
faiss_results_dir:
  /home/sdp/pmed_singularity/precision-medicine/example/faiss_results/
svs_index_dir:
  /home/sdp/pmed_singularity/precision-medicine/example/svs_index/
svs_results_dir:
  /home/sdp/pmed_singularity/precision-medicine/example/svs_results/
query_results_dir:
  /home/sdp/pmed_singularity/precision-medicine/example/svs_sample_results/

vcf_file:
  /home/sdp/pmed_singularity/precision-medicine/example/example_merge.vcf.gz
ref_map:
  /home/sdp/pmed_singularity/precision-medicine/example/example_merge.map 
database_IDs:
  /home/sdp/pmed_singularity/precision-medicine/example/database_IDs.txt
database_hap_IDs:
  /home/sdp/pmed_singularity/precision-medicine/example/database_hap_IDs.txt
query_IDs:
  /home/sdp/pmed_singularity/precision-medicine/example/query_IDs.txt
query_hap_IDs:
  /home/sdp/pmed_singularity/precision-medicine/example/query_hap_IDs.txt
encoding_file:
  /home/sdp/pmed_singularity/precision-medicine/encoding.txt

cpp_bin_dir:
  /home/sdp/pmed_singularity/precision-medicine/cpp/bin/
cpp_src_dir:
  /home/sdp/pmed_singularity/precision-medicine/cpp/src/
cpp_include_dir:
  /home/sdp/pmed_singularity/precision-medicine/cpp/include/

python_dir:
  /home/sdp/pmed_singularity/precision-medicine/python/scripts/
model_dir:
  /home/sdp/pmed_singularity/precision-medicine/pytorch/
model_checkpoint:
  /home/sdp/pmed_singularity/precision-medicine/last.ckpt
batch_size:
  128
n_workers:
  8

k:
  20
pedigree:
  0

htslib_dir:
  /home/sdp/pmed_singularity/precision-medicine/lib/htslib/
