home_dir:
  /home/sdp/precision-medicine/
conda_dir:
  /home/sdp/miniconda3/envs/pm

data_dir:
  /home/sdp/precision-medicine/example/
vcf_file:
  /home/sdp/precision-medicine/example/example.vcf
query_file:
  /home/sdp/precision-medicine/example/samples_query.txt
out_dir:
  /home/sdp/precision-medicine/example/segments/
config_file:
  /home/sdp/precision-medicine/example/config_ex.yaml


cpp_bin_dir:
  cpp/bin/
cpp_src_dir:
  cpp/src/
cpp_include_dir:
  cpp/include/
cpp_configs_dir:
  /home/sdp/precision-medicine/example/

python_dir:
  python/scripts/

htslib_dir:
  lib/htslib/
