home_dir:
./
conda_dir:
/home/sdp/miniconda3/envs/pmed/
cpp_bin_dir:
cpp/bin/
cpp_src_dir:
cpp/src/
cpp_include_dir:
cpp/include/
cpp_configs_dir:
cpp/configs/
python_dir:
python/scripts/
data_dir:
/home/sdp/precision-medicine/example/
vcf_file:
/home/sdp/precision-medicine/example/example.8-9.vcf.gz
interpolated_map:
/home/sdp/precision-medicine/example/interpolated.map
encoding_file:
/home/sdp/precision-medicine/example/encoding.txt
sample_IDs_file:
/home/sdp/precision-medicine/example/database_IDs.txt
query_file:
/home/sdp/precision-medicine/example/query_IDs.txt
out_dir:
/home/sdp/precision-medicine/example/segments/
out_base_name:
example.data
segment_size:
1
