home_dir:
./
conda_dir:
~/miniconda3/envs/pm
cpp_bin_dir:
cpp/bin/
cpp_src_dir:
cpp/src/
cpp_include_dir:
cpp/include/
cpp_configs_dir:
cpp/configs/
python_dir:
python/scripts/
data_dir:
example/
vcf_file:
example/EUR_sim.vcf
interpolated_map:
example/interpolated.map
encoding_file:
example/example_encoding.txt
sample_IDs_file:
example/samples_IDs.txt
query_file:
example/samples_query.txt
out_dir:
example/segments/
out_base_name:
example.data
segment_size:
1
