home_dir:
  ./
conda_dir:
  ~/miniconda3/envs/pmed

data_dir:
  example/
vcf_file:
  example/EUR_sim.vcf.gz
ref_map:
  /home/sdp/pmed-local/data/plink_maps/plink.chr8.GRCh38.map
interpolated_map:
  example/interpolated.map
query_file:
  example/samples_query.txt
out_dir:
  example/segments/
config_file:
  example/config_ex.yaml


cpp_bin_dir:
  cpp/bin/
cpp_src_dir:
  cpp/src/
cpp_include_dir:
  cpp/include/
cpp_configs_dir:
  example/

python_dir:
  python/scripts/

htslib_dir:
  lib/htslib/
