home_dir:
./
conda_dir:
~/miniconda3/envs/pm
cpp_bin_dir:
cpp/bin/
cpp_src_dir:
cpp/src/
cpp_include_dir:
cpp/include/
cpp_configs_dir:
cpp/configs/
python_dir:
python/scripts/
data_dir:
/home/sdp/pmed-local/data/small/
vcf_file:
/home/sdp/pmed-local/data/small/small.vcf.gz
interpolated_map:
/home/sdp/pmed-local/data/small/interpolated.map
encoding_file:
/home/sdp/pmed-local/data/small/encoding.txt
sample_IDs_file:
/home/sdp/pmed-local/data/small/database_IDs.txt
query_file:
/home/sdp/pmed-local/data/small/query_IDs.txt
out_dir:
/home/sdp/pmed-local/data/small/segments/
out_base_name:
small.data
segment_size:
1
