conda_pmed:
  conda_environments/pmed.yml
conda_model:
  conda_environments/torch-gpu.yml
conda_faiss:
  conda_environments/faiss-cpu.yml

root_dir:
  example/
log_dir:
  example/log/
benchmark_dir:
  example/benchmark/
vcf_segments_dir:
  example/vcf_segments/
encodings_dir:
  example/encodings/
embeddings_dir:
  example/embeddings/
faiss_index_dir:
  example/faiss_index/
faiss_results_dir:
  example/faiss_results/
svs_index_dir:
  example/svs_index/
svs_results_dir:
  example/svs_results/
query_results_dir:
  example/svs_sample_results/

vcf_file:
  example/example_merge.vcf.gz
ref_map:
  example/example_merge.map 
database_IDs:
  example/database_IDs.txt
database_hap_IDs:
  example/database_hap_IDs.txt
query_IDs:
  example/query_IDs.txt
query_hap_IDs:
  example/query_hap_IDs.txt
encoding_file:
  encoding.txt

cpp_bin_dir:
  cpp/bin/
cpp_src_dir:
  cpp/src/
cpp_include_dir:
  cpp/include/

python_dir:
  python/scripts/
model_dir:
  pytorch/
model_checkpoint:
  /Users/krsc0813/precision-medicine/last.ckpt
batch_size:
  128
n_workers:
  8

k:
  20
pedigree:
  0

htslib_dir:
  lib/htslib/
