conda_dir:
  /home/sdp/miniconda3/envs/pmed/
log_dir:
  example/log/

data_dir:
  example/
vcf_file:
  example/example_merge.vcf.gz
ref_map:
  example/example_merge.map  
database_IDs:
  example/database_IDs.txt
query_IDs:
  example/query_IDs.txt
out_dir:
  example/segments/
encoding_file:
  encoding.txt

cpp_bin_dir:
  cpp/bin/
cpp_src_dir:
  cpp/src/
cpp_include_dir:
  cpp/include/

python_dir:
  python/scripts/

k:
  20
delim:
  space

htslib_dir:
  lib/htslib/
faisslib_dir:
  lib/faiss/
