conda_dir:
  /home/sdp/miniconda3/envs/precision-medicine/

sample_IDs:
  data/ALL.sampleIDs

python_dir:
  python

src_dir:
  cpp/src
include_dir:
  cpp/include
bin_dir:
  cpp/bin

configs_dir:
  cpp/configs
segments_out_dir:
  data/segments/chr6/seg_5000

k:
  2548
