vcf_file:
  data/vcf/chr0-test.5000.vcf
sample_IDs:
  data/ALL.sampleIDs

bin_dir:
  cpp/bin
src_dir:
  cpp/src
include_dir:
  cpp/include
conda_dir:
  /home/sdp/miniconda3/envs/precision-medicine
python_dir:
  python

configs_dir:
  cpp/configs
segments_out_dir:
  data/segments/chr0_test/seg_5000

k:
  2548
enc_delim:
  none
emb_delim:
  space
