vcf_file:
  data/vcf/chr0-test.5000.vcf
samples_dir:
  data/samples

configs_dir:
  cpp/configs
segments_out_dir:
  data/segments/chr0_test/seg_5000

bin_dir:
  cpp/bin
src_dir:
  cpp/src
include_dir:
  cpp/include
conda_dir:
  /home/sdp/miniconda3/envs/pm
python_dir:
  python
model_dir:
  python/training_loop


batch_size:
  32

k:
  100
enc_delim:
  none
emb_delim:
  space
