sample_IDs:
  data/ALL.sampleIDs

bin_dir:
  cpp/bin
src_dir:
  cpp/src
include_dir:
  cpp/include
conda_dir:
  /home/sdp/miniconda3/envs/precision-medicine
python_dir:
  python

configs_dir:
  cpp/configs
segments_out_dir:
  data/segments/chr0_test/seg_3

k:
  3
delim:
  none
