__default__:
  job-name: "{rule}"
  partition: ami100
  time: 60
  nodes: 1
  ntasks: 4
  output: "/scratch/alpine/krsc0813/slurm_files/out/{rule}-%j.out"
  error: "/scratch/alpine/krsc0813/slurm_files/out/{rule}-%j.err"

#CreateIndex:
#  partition: long
#  time: 10080 # 1 week
#  ntasks: 64
#  mem: 512gb # probably overkill (nope...)
#
#Bwapairedsample:
#  partition: short
#  time: 1439 # almost 24hrs
#  mem: 64gb
#  ntasks: 64
#
#QueryIndex:
#  job-name: "{rule}"
#  partition: long
#  time: 10080
#  ntasks: 64
#  mem: 256gb
