__default__:
  job-name: "{rule}"
  partition: ami100
  time: 60
  nodes: 1
  ntasks: 4
  output: "/scratch/alpine/krsc0813/slurm_files/out/{rule}-%j.out"
  error: "/scratch/alpine/krsc0813/slurm_files/out/{rule}-%j.err"

__default__:
  job-name: "{rule}"
  partition: ami100
  time: 1400
  nodes: 1
  ntasks: 64
  output: "/scratch/alpine/krsc0813/slurm_files/out/{rule}-%j.out"
  error: "/scratch/alpine/krsc0813/slurm_files/out/{rule}-%j.err"

get_sample_IDs:
  time: 10
  ntasks: 1

interpolate_map:
  time: 10
  ntasks: 1

segment_boundary_file_compile:
  time: 10
  ntasks: 1

segment_boundary_file_execute:
  time: 10
  ntasks: 1

slice_VCF:
  time: 60
  ntasks: 1

encode_compile:
  time: 10
  ntasks: 1

encode_execute:
  time: 600

hap_IDs:
  time: 10
  ntasks: 1

build_faiss_index_compile:
  time: 10
  ntasks: 1

build_faiss_index_execute:
  time: 600

search_faiss_index_compile:
  time: 10
  ntasks: 1

search_faiss_index_execute:
  time: 600

#CreateIndex:
#  partition: long
#  time: 10080 # 1 week
#  ntasks: 64
#  mem: 512gb # probably overkill (nope...)
#
#Bwapairedsample:
#  partition: short
#  time: 1439 # almost 24hrs
#  mem: 64gb
#  ntasks: 64
#
#QueryIndex:
#  job-name: "{rule}"
#  partition: long
#  time: 10080
#  ntasks: 64
#  mem: 256gb
