conda_dir:
  /home/sdp/miniconda3/envs/precision-medicine/

src_dir:
  cpp/src
include_dir:
  cpp/include
bin_dir:
  cpp/bin

configs_dir:
  cpp/configs
segments_out_dir:
  data/segments/chr0-test/seg_3

k:
  2548
