model: "/data/exploration/resampled_data.checkpoints/siamese-conv1d-epoch=01-val_loss=0.09.ckpt"
gpu: True
samples_list: "/data/sample_list.txt"
sample_table: "/data/1kg_sample_table.tsv"
segments_dir: "/data/segments/"
input_files:
  - "/data/segments/segment.10.pos"
  - "/data/segments/segment.11.pos"
  - "/data/segments/segment.12.pos"
  - "/data/segments/segment.13.pos"
  - "/data/segments/segment.14.pos"
outdir: "/data/test_encodings"
batch_size: 128
num_workers: 4
num_neighbors: 50
