# model: "/home/murad/Repositories/precision-medicine/pytorch/high_lr2.checkpoints/siamese-epoch-02d=0-val_loss-.2f=0.ckpt"
model: "/data/exploration/resampled_data.checkpoints/siamese-conv1d-epoch=01-val_loss=0.09.ckpt"
gpu: True
samples_list: "/data/sample_list.txt"
sample_table: "/data/1kg_sample_table.tsv"
segments_dir: "/data/segments/"
input_files:
  # - "/data/segments/1KG.data.seg.163.pos_encoded"
  # - "/data/segments/1KG.data.seg.164.pos_encoded"
  # - "/data/segments/1KG.data.seg.165.pos_encoded"
  # - "/data/segments/1KG.data.seg.166.pos_encoded"
  # - "/data/segments/1KG.data.seg.167.pos_encoded"
  - "/data/segments/segment.10.pos"
  - "/data/segments/segment.11.pos"
  - "/data/segments/segment.12.pos"
  - "/data/segments/segment.13.pos"
  - "/data/segments/segment.14.pos"
outdir: "/data/test_encodings"
batch_size: 128
num_workers: 4
num_neighbors: 50
