
# data prep config ------------------------------------------------------------
random_seed: 42
segment_prefix: "segment"
gt_ext: "gt" # no dots
pos_ext: "pos"
file_segment_delimiter: "."
seg_offset: -2 # position in filename after splitting by delimiter
num_pairings: 5 # n pairings for each sample from each subpopulation
samples_list: "/data/sample_list.txt"
sample_table: "/data/1kg_sample_table.tsv"
segments_dir: "/data/segments"
outdir: "/data/exploration"

model_config: "/home/murad/Repositories/precision-medicine/pytorch/conf/convnext_config.yaml"
model_prefix: 'test' # TODO this is annoying but i need it here
