home_dir:
  ./
conda_dir:
  ~/miniconda3/envs/pmed/

data_dir:
  ../pmed-local/data/EAS/
vcf_file:
  ../pmed-local/data/EAS/EAS_unrelated.vcf
query_file:
  ../pmed-local/data/EAS/EAS_queries.txt
out_dir:
  ../pmed-local/data/EAS/segments/
config_file:
  notes/ancestry_configs/config_EAS.yaml


cpp_bin_dir:
  cpp/bin/
cpp_src_dir:
  cpp/src/
cpp_include_dir:
  cpp/include/
cpp_configs_dir:
  notes/ancestry_configs

python_dir:
  python/scripts/

htslib_dir:
  lib/htslib/
