home_dir:
  ./
conda_dir:
  ~/miniconda3/envs/pm/

data_dir:
  ../pmed-local/data/1KG/
vcf_file:
  ../pmed-local/data/1KG/1kGP_high_coverage_Illumina.chr8.filtered.SNV_INDEL_SV_phased_panel.vcf
database_file:
  ../pmed-local/data/1KG/all_hap_IDs.txt
query_file:
  ../pmed-local/data/1KG/test_query.txt
ref_map:
  /home/sdp/pmed-local/data/plink_maps/plink.chr8.GRCh38.map
interpolated_map:
  /home/scp/pmed-local/data/1KG/interpolated.map
out_dir:
  ../pmed-local/data/1KG/segments/
config_file:
  notes/ancestry_configs/config_1KG.yaml
k:
  10
delim:
  space

cpp_bin_dir:
  cpp/bin/
cpp_src_dir:
  cpp/src/
cpp_include_dir:
  cpp/include/
cpp_configs_dir:
  notes/ancestry_configs

python_dir:
  python/scripts/

htslib_dir:
  lib/htslib/
faisslib_dir:
  lib/faiss/
