home_dir:
./
conda_dir:
~/miniconda3/envs/pm
cpp_bin_dir:
cpp/bin/
cpp_src_dir:
cpp/src/
cpp_include_dir:
cpp/include/
cpp_configs_dir:
cpp/configs/
python_dir:
python/scripts/
data_dir:
../pmed-local/data/1KG/
vcf_file:
../pmed-local/data/1KG/1kGP_high_coverage_Illumina.chr8.filtered.SNV_INDEL_SV_phased_panel.vcf
map_file:
../pmed-local/data/plink_maps/plink.chr8.GRCh38.map
encoding_file:
example/example_encoding.txt
sample_IDs_file:
../pmed-local/data/1KG/samples_IDs.txt
query_file:
../pmed-local/data/1KG/sample_IDs.txt
out_dir:
../pmed-local/data/1KG/segments/
out_base_name:
1KG.data
segment_size:
1
