home_dir:
./
conda_dir:
~/miniconda3/envs/pm
cpp_bin_dir:
cpp/bin/
cpp_src_dir:
cpp/src/
cpp_include_dir:
cpp/include/
cpp_configs_dir:
cpp/configs/
python_dir:
python/scripts/
data_dir:
../pmed-local/data/EAS/
vcf_file:
../pmed-local/data/EAS/EAS_unrelated.vcf.gz
map_file:
../pmed-local/data/.map
encoding_file:
example/example_encoding.txt
sample_IDs_file:
../pmed-local/data/samples_IDs.txt
query_file:
../pmed-local/data/EAS/samples_query.txt
out_dir:
../pmed-local/data/EAS/segments/
out_base_name:
EAS_unrelated.data
segment_size:
1
