home_dir:
  /home/sdp/precision-medicine/
conda_dir:
  /home/sdp/miniconda3/envs/pm

data_dir:
  /home/sdp/precision-medicine/data/ped_sim_data/GBR/
vcf_file:
  /home/sdp/precision-medicine/data/ped_sim_data/GBR/GBR.simulated.vcf
query_file:
  /home/sdp/precision-medicine/data/ped_sim_data/GBR/GBR_queryIDs.txt
out_dir:
  /home/sdp/precision-medicine/data/ped_sim_data/GBR/segments/


cpp_bin_dir:
  cpp/bin/
cpp_src_dir:
  cpp/src/
cpp_include_dir:
  cpp/include/
cpp_configs_dir:
  cpp/configs/

python_dir:
  python/scripts/
