__default__:
    job-name: "{rule}"
    partition: short
    time: 60
    gpu: gpu:0
    nodes: 1
    nodelist: fijinode-36
    ntasks: 4
    mem: 32gb
    output: "/home/name/precision-medicine/example/out/{rule}.out"
    error: "/home/name/precision-medicine/example/err/{rule}.err"

remove_empty_encoding:
    time: 10

remove_intermediate_files:
    time: 10

hap_IDs:
    time: 1

model:
    partition: nvidia-a100
    nodelist: fijigpu-04
    gpu: gpu:1
    time: 360

split_embeddings:
    time: 360
