__default__:
    job-name: "{rule}"
    partition: long
    time: 3600
    gpu: gpu:0
    nodes: 1
    ntasks-per-node: 16
    mem: 32gb
    output: "/Users/krsc0813/1KG_data/example/out/{rule}.out"
    error: "/Users/krsc0813/1KG_data/example/err/{rule}.err"

model:
    partition: nvidia-a100
    nodelist: fijigpu-06
    gpu: gpu:1
    time: 3600
