__default__:
    job-name: "{rule}"
    partition: short
    time: 60
    gpu: gpu:0
    nodes: 1
    nodelist: fijinode-36
    ntasks-per-node: 4
    mem: 32gb
    output: "/Users/krsc0813/1KG_data/example/out/{rule}.out"
    error: "/Users/krsc0813/1KG_data/example/err/{rule}.err"

model:
    partition: nvidia-a100
    nodelist: fijigpu-04
    gpu: gpu:1
    time: 3600
